[global]
pid=/var/run/php-fpm.pid
error_log=/var/log/php-fpm-error.log
daemonize=no

[www]
user=developer
group=developer

listen=0.0.0.0:9000
listen.mode=0660

pm=dynamic
pm.max_children=40
pm.start_servers=10
pm.min_spare_servers=10
pm.max_spare_servers=20

access.log=/var/log/php-fpm-access.log
slowlog=/var/log/php-fpm-slow.log

request_terminate_timeout=60s
request_slowlog_timeout=5s

rlimit_files=50000
